services:
  wc_db_qcp:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOTPASS:-ABC123}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
      MYSQL_USER: ${WORDPRESS_DB_USER:-wordpress}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASS:-wordpress}
    # volumes:
    #   - ./data/wc_db_qcp:/var/lib/mysql
  woocommerce:
    container_name: woocommerce_qcp
    build:
      context: docker/wordpress/
      dockerfile: Dockerfile
    depends_on:
      - wc_db_qcp
    ports:
      - ${PORT_HTTP:-8010}:80
      - ${PORT_SSL:-8444}:443
    volumes:
      - ./:/tmp/plugin:ro
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-wc_db_qcp}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASS: ${WORDPRESS_DB_PASS:-wordpress}
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
      WORDPRESS_LOCALE: ${WORDPRESS_LOCALE:-en_US}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE:-QSHOP}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER:-admin}
      WORDPRESS_ADMIN_PASS: ${WORDPRESS_ADMIN_PASS:-admin123}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL:-admin@admin.com}
      WORDPRESS_URL: ${WORDPRESS_HOST}
      PLUGIN_VERSION: ${PLUGIN_VERSION}
      PLUGIN_URL: ${PLUGIN_URL:-local}
      NGROK_TOKEN: ${NGROK_TOKEN}
      DEFAULT_COUNTRY_CODE: ${DEFAULT_COUNTRY_CODE:-AT}
      GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}
      GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
      GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}
      GITHUB_SHA: ${GITHUB_SHA}
      GITHUB_REF: ${GITHUB_REF}
